### ISSUE TITLE
Custom Types and Their Related Transitions

### ISSUE THREAD

**Issue by jbolda** [microstates/microstates.js#236]
A very interesting concept you have here! I thought I would do a few experiments first to see if this is something I can bring into a project. There are currently the 5 primitives that you can use. Is it possible to define your own custom types? I have been using [big.js](https://github.com/MikeMcl/big.js/) for numbers as it has many of the safe math operations. The current Number primitive only has the `increment` and `decrement` methods available. Ideally I would like to use big.js directly as a type. Alternatively, can you define your own methods on a type? Apologies if I mixed up my terminology... getting used to the microstates naming still.

I did some experimenting in codesandbox.io if that will help get my intention across:
[![Edit Microstates and Big.js](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/lj7zo6xl)

**Comment by cowboyd** [comment]
Hi there! That's a great question.

It sounds like what you're interested in is "how do I make a new primitive value?"

The answer is that you want to "wrap" the new primitive with a microstate just in the same way you would wrap an existing primitive like `Number` or `String`.

In this case. You would always convert the value of the microstate into an instance of a `big.js` `Big`

```
import { default as _Big } from "big.js";

class Big {
  initialize(value = 0) {
    return value instanceof _Big ? value : _Big(Number(value));
  }

  add(value) {
    return this.state.add(value);
  }
}
```

Notice how my initializer checks and if we're already a bignum, then we just use that bignum value, otherwise, we "promise" the javascript number to a bignum.

https://codesandbox.io/s/4zpw8orp47


Final note, the syntax of this will change slightly with the upcoming release of `0.11.0` because _only_ primitive values will have the `state` property, so you'll have to explicitly declare your `Big` class as a primitive. The `0.11.0` version of this will look like:

```js
import { default as _Big } from "big.js";
import { Primitive } from "microstates";

class Big extends Primitive {
  initialize(value = 0) {
    return value instanceof _Big ? value : _Big(Number(value));
  }

  add(value) {
    return this.state.add(value);
  }
}
```

**Comment by cowboyd** [comment]
Marking this as closed, but feel free to ask any further questions in the [gitter channel](https://gitter.im/microstates/microstates.js)

**Comment by jbolda** [comment]
This worked lovely! I started bringing it in, but it's a bit of a long rewrite on a side project nonetheless. Looking forward to digging in more.
