### ISSUE TITLE
Default values lost on Paramaterized Array types

### ISSUE THREAD

**Issue by brandynbennett** [microstates/microstates.js#292]
Given: 

```js
class Sort {
  column = String;
  dir = create(String, "asc");
}

class Table {
  sorts = [Sort];
}

let table = create(Table, {
  sorts: [{ column: "foo" }]
});

console.log(valueOf(table.sorts)[0].dir); // undefined
```

The default `dir` of `"asc"` is lost after calling `valueOf`. 

See example: https://codesandbox.io/s/nzkq7v4m0

**Comment by cowboyd** [comment]
@brandynbennett This is a weird one, and the only reason we haven't addressed it yet is because we're not 100% sure on what the final way will be to express default values.

The problem is that the default is _not_ part of the `valueOf()`, `valueOf()` is literally the value of the original POJO + any transitions that act upon it. One way to think of microstates is just a box that you place a POJO into. Once it's inside, you can query it for information. `valueOf()` is the function you use to take the value back out of the box.

In this case, you put in 

```js
{
  sorts: [{ column: "foo" }]
}
```

And so there's no associated value at the path `sorts.0.dir`


See here for a similar situation and explanation as to why this is tricky. https://github.com/microstates/microstates.js/pull/277

One solution would be for us to apply defaults whenever there is a transition. That would, I think let us remain lazy and infinitely recursive, but still have defaults make sense.

Another would be to have a different way of expressing defaults..

**Comment by brandynbennett** [comment]
@taras @cowboyd Thanks so much for the responses. This makes sense. Definitely not an easy problem. Thanks for the destructuring tip, didn't realize I could get at the individual values that way.
