### ISSUE TITLE
Proposal for composition Microstates Effects

### ISSUE THREAD

**Issue by taras** [microstates/microstates.js#331]
We have a fairly well-established model primitive that allows us to construct trees of state.
We now need to find a way to ergonomically wrap nodes in the state tree in functions that 
will manage side effects at the node's location.

This mechanism needs to be composable to allow domain-specific async behavior to be written in isolation and combined to form larger data structures. There are several challenges in designing such a mechanism. 

The model is defined separately from the async handling. The async decoration needs to
happen without modifying the original type to preserve the integrity of the type and allow it to 
be decorated many times without conflict.

Type definitions are class-based which, in JavaScript, are just functions. There is no reliable way
to immutably decorate classes without relying on eval. This forces us to look at other mechanisms for referencing locations in a Microstate Type.

Microstates have a pattern that allows for the users to implicitly reference location by statically
referencing location in a Microstate tree. I propose that we use a similar mechanism to allow users to reference locations in a Microstate that they wish to decorate. In the past, we've referred to this pattern as *telescopic*. It uses dot notation to reference a path in the Microstate. 

Let's use Charles' [microstates-bluetooth](https://github.com/cowboyd/microstates-bluetooth/blob/master/cli/main.js#L17) example because it provided inspiration for this proposal.

This example has 3 definitive stages.

1. create initial microstate
2. create a chain of effects
3. create store using initial microstate and chain of effects

In the *microstates-bluetooth* example, the Effects chain is constructed with `Effects([currentReference, repaint, bluetoothController, scanController])`. The Effects constructor takes an array of functions and returns a function that will invoke the received functions in sequence. 

The challenge with this approach is that there is currently no way to reference specific locations in the tree. Instead, we have to manually extract the microstate that the effect is operating on. You can see this [here](https://github.com/cowboyd/microstates-bluetooth/blob/master/cli/main.js#L54),

```js
function scanController(bluetooth) {
  let { scan } = bluetooth;
  if (scan.isActivating) {
    let active = scan.activate();
    noble.startScanning([], true);
  } else if (scan.isDeactivating) {
    scan.deactivate();
    noble.stopScanning();
  }
}
```

I propose that we introduce a telescopic way to reference locations in the microstate tree. The result will be the same but instead of manually finding the location in the effect function, we'll extract the microstate using the path defined when creating the effect.

To do this, `Effects` constructor will receive a function that will receive the root of the effect composition tree as an argument. The argument will be a function that represents the root and have telescopic properties to reference paths. Each invocation will return a function. We can rewrite the example in the following way.

```js
let storeEffects = Effects(
  root => root(currentReference)
    (root(repaint))
    (root(bluetoothController))
    (root.scan(scanController))
)
```

Then the `scanController` effect function can receive the scan without the root.

```js
function scanController(scan) {
  if (scan.isActivating) {
    let active = scan.activate();
    noble.startScanning([], true);
  } else if (scan.isDeactivating) {
    scan.deactivate();
    noble.stopScanning();
  }
}
```

One of the problems with this approach is that calling `root` is very verbose. We can add some sugar that will automatically assume root when the change has a regular function that is not a root created function. With the sugar, it would look like this.

```js
let bluetoothEffects = Effects(
  root => root(currentReference)
    (repaint)
    (bluetoothController)
    (root.scan(scanController))
)
```

Once we have the effects, we can pass them into the store as we've done previously.

```js
let bluetooth = Store(initial, bluetoothEffects);
```

These effect functions can be composed a similar matter. Let's say we have the bluetooth manager as part of a CLI type.

```js
class CLI {
  bluetooth = Bluetooth
}

let effects = Effects(root => root.bluetooth(bluetoothEffects))

let cliStore = Store(create(CLI), effects);
```

## Alternatives

We could also accomplish similar composition without telescopic paths by using arrays of paths.

```js
let storeEffects = Effects(
  root => root([], currentReference)
    (root([], repaint))
    (root([], bluetoothController))
    (root(['scan'], scanController))
)
```

This would effectively do the same thing as what telescopic mechanism does under the hood.

**Comment by mharris717** [comment]
A toy example using the method under `Alternatives` might help people better understand your proposal.

**Comment by taras** [comment]
@mharris717 updated, see this makes sense.

**Comment by cowboyd** [comment]
We could fix the problem of `root` being verbose by using a chaining syntax for `Effect` itself:

```js
Effect() // implicit path [], implicit effect is no-op x => x
  .do(repaint)
  .do(currentReference)
  .do(bluetoothController)
  .doAt('scan', scanController)
  
```

There are a couple things to consider how to handle effects.

### Enumeration

We have to be able to specify effects for arrays and objects for which we won't know the path of ahead of time. An example is the peripherals, how do we register an effect over an entire list of peripherals

#### Structure

Effects need to be organized in a tree, and evaluated from the top to the bottom. For example, if we have an effect that is waiting to run on a peripheral, but we turn bluetooth _off_, which removes all the peripherals, then we need to do two things:

1. _not_ run any pending effects on the list of peripherals
2. run any teardown on each effect that is active and associated with one of the peripherals being removed.

#### Intermediate States (optional, but nice to have)

One thing I've noticed is that async operations generally have a state machine that looks like roughly.

1. NotDoingTheThing
2. RequestHasBeenIssuedToDoTheThing
3. NowDoingTheThing
4. RequestIssuedToNotDoTheThingAnymore
5. NotDoingTheThing (Same state as 1)

In the case of the scan, these are

1. Idle
2. Activating
3. Active
4. Deactivating
5. Idle

The `Activating` and `Deactivating` states exist only to represent the transition between `Idle` and `Active` and while this is correct and necessary, it would be nice to be able to factor them out somehow in order to avoid doubling the number of states needed to represent every since async transition.

I was thinking something like this

```js
import { each } from '@microstates/effects';

const scanController = each({ isOn: true, scan: each({ isActivating: true })}, *(scan) => {
  noble.startScanning();
  yield scan.activate();
}).each({}, scan: each({isDeactivating: true}), *scan => {
  noble.stopScanning();
  yield scan.deactivate();
});
```

The reason we yield is to indicate that we're performing a state transition and so there is a new top level state, so we don't need to run any of the subsequent effects down the tree, but should start again matching from the top.

```js
const peripheralController = each

**Comment by cowboyd** [comment]
This is going to be superseded by http://github.com/thefrontside/effection
