### ISSUE TITLE
Allow microstates for type-shifting and chaining inside parameterized types.

### ISSUE THREAD

**Issue by cowboyd** [microstates/microstates.js#76]
Let's say I have a `Form` object with a list of `Field` states. Every field has its initial input, and a way to revert its input _back_ to the initial value.

```js
class Field {
  initialValue = String;
  input = String;
  reset() {
    return this.input.set(this.state.initialValue);
  }
}
class Form {
  name = String;
  fields = [ Field ]
}
```

Then, suppose I want to have a `reset` transition at the form level that resets _all_ of the fields back to their initial value:

```js
class Form {
  //....
  reset() {
    return this.fields.map(field => field.reset());
  }
}
```
This is currently impossible because the object passed to the `map` function is not a `Field` microstate, it is the `valueOf()` the `Field` microstate.

We need a way to access the transitions of the parameterized type, so that they can compose just as easily as a normal transition.... This includes typeshifting.

This testcase fails:

```js
describe('Mapping parameterized Arrays', function() {
  class Thing {
    description = String;
  }

  class Bling {
    description = String;
  }

  it('loses type in a map', function() {
    let array = create([Thing], [{description: "fun"}])
        .map(item => create(Bling, item));
    expect(array.state.length).toBe(1);
    expect(array.state[0]).toBeInstanceOf(Bling);
  });
});
```

This might be related to #75

**Comment by taras** [comment]
With #113, we now have the ability to manipulate a microstate's tree. This can allow us to chain operations inside of map on Objects and Arrays. It's unclear what API map operations should have. 

Currently, the map function receives the state of the particular item that is being mapped. In the case of `create([Thing], [{description: "fun"}]).map(item => item)`, map will receive an instance of Thing. This API does not provide an obvious way to performed chained operations inside of the map function.

Should map function receive a microstate for that particular item? This will allow to chain operations for example, `create([Thing], [{description: "fun"}]).map(item => item.description.concat('!!!))` would work. 

Unfortunately, this means that working with simpler map operation is not as obvious because the state needs to accessed from state property on the microstate. For example, to apply an operation to each item in an array, you would need to do something like `create([Number], [1, 2, 3]).map(n => n.state * n.state)`. 

What do you think about this?
